# Generated by Django 4.1.5 on 2023-01-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='HomeMenu name')),
                ('name1', models.CharField(max_length=50, verbose_name='HomeMenu name')),
                ('name2', models.CharField(max_length=50, verbose_name='HomeMenu name')),
                ('name3', models.CharField(max_length=50, verbose_name='HomeMenu name')),
                ('name4', models.CharField(max_length=50, verbose_name='HomeMenu name')),
                ('name5', models.CharField(max_length=50, verbose_name='HomeMenu name')),
                ('name6', models.CharField(max_length=50, verbose_name='HomeMenu name')),
                ('about', models.TextField(verbose_name='HomeMenu about')),
                ('about1', models.TextField(verbose_name='HomeMenu about')),
                ('about2', models.TextField(verbose_name='HomeMenu about')),
                ('about3', models.TextField(verbose_name='HomeMenu about')),
                ('about4', models.TextField(verbose_name='HomeMenu about')),
                ('about5', models.TextField(verbose_name='HomeMenu about')),
                ('about6', models.TextField(verbose_name='HomeMenu about')),
                ('about7', models.TextField(verbose_name='HomeMenu about')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeMenu image')),
            ],
        ),
    ]
