# Generated by Django 4.1.5 on 2023-01-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemenu',
            name='about1',
            field=models.TextField(verbose_name='HomeMenu about1'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='about2',
            field=models.TextField(verbose_name='HomeMenu about2'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='about3',
            field=models.TextField(verbose_name='HomeMenu about3'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='about4',
            field=models.TextField(verbose_name='HomeMenu about4'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='about5',
            field=models.TextField(verbose_name='HomeMenu about5'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='about6',
            field=models.TextField(verbose_name='HomeMenu about6'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='about7',
            field=models.TextField(verbose_name='HomeMenu about7'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='name1',
            field=models.CharField(max_length=50, verbose_name='HomeMenu name1'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='name2',
            field=models.CharField(max_length=50, verbose_name='HomeMenu name2'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='name3',
            field=models.CharField(max_length=50, verbose_name='HomeMenu name3'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='name4',
            field=models.CharField(max_length=50, verbose_name='HomeMenu name4'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='name5',
            field=models.CharField(max_length=50, verbose_name='HomeMenu name5'),
        ),
        migrations.AlterField(
            model_name='homemenu',
            name='name6',
            field=models.CharField(max_length=50, verbose_name='HomeMenu name6'),
        ),
    ]
