# Generated by Django 4.1.5 on 2023-01-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_homemenu_about1_alter_homemenu_about2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homemenu',
            options={'verbose_name': 'HomeMenu', 'verbose_name_plural': 'HomeMenues'},
        ),
    ]
