# Generated by Django 4.1.5 on 2023-01-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_homemenu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='SingleImage name')),
                ('about', models.TextField(verbose_name='SingleImage about')),
                ('about1', models.TextField(verbose_name='SingleImage about1')),
                ('img', models.ImageField(upload_to='media', verbose_name='SingleImage image')),
            ],
            options={
                'verbose_name': 'SingleImage',
                'verbose_name_plural': 'SingleImages',
            },
        ),
    ]
